language: c

sudo: required

env:
  global:
    - PREFIX=$HOME/target

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq help2man libpcsclite-dev
  
install: true

script:
  - make PREFIX=$PREFIX
